# Generated by Django 5.2.4 on 2025-08-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_group_owner_grouptask_groupsubtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptask',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
